
package sudoku;

import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import javax.swing.JOptionPane;

/**
 *
 * @author jomel
 */
public class SudokuJuego extends javax.swing.JFrame implements KeyListener{

    TableroSudoku clase = new TableroSudoku();
    int[][] tablero = clase.getTablero();
    javax.swing.JTextField[][] visual= new javax.swing.JTextField[9][9]; 
    
    public SudokuJuego(int dif) {
        initComponents();
        for(int fil=0; fil<9; fil++){
            for(int col=0; col<9; col++){
                visual[fil][col] = new javax.swing.JTextField();
                visual[fil][col].setBounds(fil*500/9 + 10,col*500/9 + 75,500/9,500/9);
                visual[fil][col].setFont(new java.awt.Font("Times New Roman", 1, 24));
                visual[fil][col].addKeyListener(this);
                add(visual[fil][col]);
            }
        }
        
        Mostrar(dif);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Sudoku");

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jButton1.setText("Resolver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(475, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 385, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(Victoria()){
            JOptionPane.showMessageDialog(this, "Gano, el orden no era asi.");
        }else{
            JOptionPane.showMessageDialog(this, "Perdio, el orden no era asi.");
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private boolean Victoria(){
        try{
            for(int fil=0; fil<9; fil++){
            for(int col=0; col<9; col++){
                if(Integer.parseInt(visual[fil][col].getText()) != tablero[col][fil]){
                    return false;
                }
            }
        }
        
        return true;
        }catch(Exception e){
            return false;
        }
    }
    
    public void keyTyped(KeyEvent e) {
        int tecla = e.getKeyChar();
        boolean valido = tecla >= 48 && tecla <= 57;

        if(!valido){
            e.consume();
        }
    }
    public void keyPressed(KeyEvent e) {
        
    }
    public void keyReleased(KeyEvent e) {
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    private void Mostrar(int dif) {
        for(int ciclo = 0; ciclo<dif; ciclo++){
            java.util.Random random = new java.util.Random();
            int fila = random.nextInt(8);
            int columna = random.nextInt(8);
            try{
                Integer.parseInt(visual[fila][columna].getText());
            }catch(Exception e){
                visual[fila][columna].setText(Integer.toString(tablero[columna][fila]));
                visual[fila][columna].setEditable(false);
            }
        }
    }
}
